/**
 * Model configuration for the native explorer
 *
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file is generated by scripts/sync-config.ts from the immutable source:
 * https://github.com/ncsizemore/jheem-backend/blob/597b5ea01702f41e2b00c2463ec4907ce7173831/.github/config/models.json
 *
 * To update, run: npm run sync-config
 */

export interface ScenarioConfig {
  id: string;
  label: string;
  description: string;
  timeline?: {
    serviceInterruptionStartTime: number;
    suppressionEffectStartTime: number;
    serviceResumeTime?: number;
    suppressionRecoveryEndTime?: number;
  };
}

export interface CustomSimParameter {
  id: string;
  label: string;
  keyPrefix: string;
  default: number;
  unit: string;
}

export interface CustomSimulationConfig {
  interventionType?: string;
  timing?: {
    interventionStartTime: number;
    lossLagYears: number;
    simulationStartYear: number;
    simulationEndYear: number;
    reportingStartYear: number;
    reportingEndYear: number;
  };
  cacheKeyPrefix?: string;
  parameters: CustomSimParameter[];
}

export interface ModelConfig {
  // Basic info
  id: string;
  name: string;
  shortName: string;
  description: string;

  // Geography
  geographyType: 'city' | 'state';
  geographyLabel: string;
  geographyLabelPlural: string;

  // Locations (from models.json full list)
  locations: string[];

  // Data source
  dataUrl: string;
  summaryFileName: string;

  // Scenarios
  scenarios: ScenarioConfig[];

  // Default selections
  defaults: {
    outcome: string;
    statistic: string;
  };

  // Available facet dimensions for this model
  facetDimensions: ('age' | 'sex' | 'race' | 'risk')[];

  // Map settings
  map: {
    center: [number, number];
    zoom: number;
  };

  // Timeline settings
  interventionStartYear: number;

  // Custom simulation support (if model supports user-specified parameters)
  customSimulation?: CustomSimulationConfig;
}

// =============================================================================
// MODEL CONFIGURATIONS
// =============================================================================

export const ryanWhiteConfig: ModelConfig = {
  id: 'ryan-white',
  name: 'Ryan White MSA Explorer',
  shortName: 'Ryan White (Cities)',
  description: 'City-level analysis of Ryan White funding scenarios across 31 Metropolitan Statistical Areas',

  geographyType: 'city',
  geographyLabel: 'City',
  geographyLabelPlural: 'Cities',

  locations: ['C.12060', 'C.12420', 'C.12580', 'C.12940', 'C.14460', 'C.16740', 'C.16980', 'C.17460', 'C.18140', 'C.19100', 'C.19820', 'C.26420', 'C.26900', 'C.27260', 'C.29820', 'C.31080', 'C.32820', 'C.33100', 'C.35380', 'C.35620', 'C.36740', 'C.37980', 'C.38060', 'C.40140', 'C.40900', 'C.41700', 'C.41740', 'C.41860', 'C.42660', 'C.45300', 'C.47900'],

  dataUrl: 'https://d320iym4dtm9lj.cloudfront.net/ryan-white',
  summaryFileName: 'city-summaries.json',

  scenarios: [
    {
      id: 'cessation',
      label: 'Cessation',
      description: 'Permanent end to Ryan White funding',
      timeline: {"serviceInterruptionStartTime":2025.5,"suppressionEffectStartTime":2025.75},
    },
    {
      id: 'brief_interruption',
      label: 'Brief Interruption',
      description: '18-month funding gap, then services resume',
      timeline: {"serviceInterruptionStartTime":2025.5,"suppressionEffectStartTime":2025.75,"serviceResumeTime":2027,"suppressionRecoveryEndTime":2028},
    },
    {
      id: 'prolonged_interruption',
      label: 'Prolonged Interruption',
      description: '42-month funding gap, then services resume',
      timeline: {"serviceInterruptionStartTime":2025.5,"suppressionEffectStartTime":2025.75,"serviceResumeTime":2029,"suppressionRecoveryEndTime":2030},
    },
  ],

  defaults: {
    outcome: 'incidence',
    statistic: 'mean.and.interval',
  },

  facetDimensions: ['age', 'sex', 'race', 'risk'],

  map: {
    center: [-96.5, 38.5],
    zoom: 4.1,
  },

  interventionStartYear: 2025,

  customSimulation: {
    interventionType: 'permanent_cessation',
    timing: {"interventionStartTime":2025.5,"lossLagYears":0.25,"simulationStartYear":2025,"simulationEndYear":2035,"reportingStartYear":2025,"reportingEndYear":2030},
    parameters: [
      { id: 'adap_loss', label: 'ADAP suppression loss', keyPrefix: 'a', default: 50, unit: '%' },
      { id: 'oahs_loss', label: 'OAHS suppression loss', keyPrefix: 'o', default: 30, unit: '%' },
      { id: 'other_loss', label: 'Other suppression loss', keyPrefix: 'r', default: 40, unit: '%' },
    ],
  },
};

export const ajphStateLevelConfig: ModelConfig = {
  id: 'ryan-white-state-ajph',
  name: 'Ryan White State Analysis (AJPH)',
  shortName: 'AJPH (11 States)',
  description: 'State-level analysis from the 2025 AJPH paper, covering 11 states',

  geographyType: 'state',
  geographyLabel: 'State',
  geographyLabelPlural: 'States',

  locations: ['AL', 'CA', 'FL', 'GA', 'IL', 'LA', 'MO', 'MS', 'NY', 'TX', 'WI'],

  dataUrl: 'https://d320iym4dtm9lj.cloudfront.net/ryan-white-state',
  summaryFileName: 'state-summaries.json',

  scenarios: [
    {
      id: 'cessation',
      label: 'Cessation',
      description: 'Permanent end to Ryan White funding',
      timeline: {"serviceInterruptionStartTime":2025.5,"suppressionEffectStartTime":2025.75},
    },
    {
      id: 'brief_interruption',
      label: 'Brief Interruption',
      description: '18-month funding gap, then services resume',
      timeline: {"serviceInterruptionStartTime":2025.5,"suppressionEffectStartTime":2025.75,"serviceResumeTime":2027,"suppressionRecoveryEndTime":2028},
    },
    {
      id: 'prolonged_interruption',
      label: 'Prolonged Interruption',
      description: '42-month funding gap, then services resume',
      timeline: {"serviceInterruptionStartTime":2025.5,"suppressionEffectStartTime":2025.75,"serviceResumeTime":2029,"suppressionRecoveryEndTime":2030},
    },
  ],

  defaults: {
    outcome: 'incidence',
    statistic: 'mean.and.interval',
  },

  facetDimensions: ['age', 'sex', 'race', 'risk'],

  map: {
    center: [-96.5, 38.5],
    zoom: 4.1,
  },

  interventionStartYear: 2025,

  customSimulation: {
    interventionType: 'permanent_cessation',
    timing: {"interventionStartTime":2025.5,"lossLagYears":0.25,"simulationStartYear":2025,"simulationEndYear":2035,"reportingStartYear":2025,"reportingEndYear":2030},
    parameters: [
      { id: 'adap_loss', label: 'ADAP suppression loss', keyPrefix: 'a', default: 50, unit: '%' },
      { id: 'oahs_loss', label: 'OAHS suppression loss', keyPrefix: 'o', default: 30, unit: '%' },
      { id: 'other_loss', label: 'Other suppression loss', keyPrefix: 'r', default: 40, unit: '%' },
    ],
  },
};

export const croiStateLevelConfig: ModelConfig = {
  id: 'ryan-white-state-croi',
  name: 'Ryan White State Analysis (CROI)',
  shortName: 'CROI (30 States)',
  description: 'State-level analysis for CROI 2026 conference, covering 30 states with conservative scenarios',

  geographyType: 'state',
  geographyLabel: 'State',
  geographyLabelPlural: 'States',

  locations: ['AL', 'AR', 'AZ', 'CA', 'CO', 'FL', 'GA', 'IL', 'IN', 'KY', 'LA', 'MA', 'MD', 'MI', 'MN', 'MO', 'MS', 'NC', 'NJ', 'NV', 'NY', 'OH', 'OK', 'PA', 'SC', 'TN', 'TX', 'VA', 'WA', 'WI'],

  dataUrl: 'https://d320iym4dtm9lj.cloudfront.net/ryan-white-state-croi',
  summaryFileName: 'state-summaries.json',

  scenarios: [
    {
      id: 'cessation',
      label: 'Cessation',
      description: 'Permanent end to Ryan White funding starting in July 2026',
      timeline: {"serviceInterruptionStartTime":2026.5,"suppressionEffectStartTime":2026.75},
    },
    {
      id: 'interruption',
      label: 'Interruption',
      description: '2.5-year funding gap; services resume in January 2029',
      timeline: {"serviceInterruptionStartTime":2026.5,"suppressionEffectStartTime":2026.75,"serviceResumeTime":2029,"suppressionRecoveryEndTime":2030},
    },
    {
      id: 'cessation_conservative',
      label: 'Cessation (Conservative)',
      description: 'Permanent cessation with conservative impact assumptions',
      timeline: {"serviceInterruptionStartTime":2026.5,"suppressionEffectStartTime":2026.75},
    },
    {
      id: 'interruption_conservative',
      label: 'Interruption (Conservative)',
      description: '2.5-year gap with conservative impact assumptions; services resume in January 2029',
      timeline: {"serviceInterruptionStartTime":2026.5,"suppressionEffectStartTime":2026.75,"serviceResumeTime":2029,"suppressionRecoveryEndTime":2030},
    },
  ],

  defaults: {
    outcome: 'incidence',
    statistic: 'mean.and.interval',
  },

  facetDimensions: ['age', 'sex', 'race', 'risk'],

  map: {
    center: [-96.5, 38.5],
    zoom: 4.1,
  },

  interventionStartYear: 2026,

  customSimulation: {
    interventionType: 'permanent_cessation',
    timing: {"interventionStartTime":2026.5,"lossLagYears":0.25,"simulationStartYear":2026,"simulationEndYear":2036,"reportingStartYear":2026,"reportingEndYear":2031},
    cacheKeyPrefix: 't2026',
    parameters: [
      { id: 'adap_loss', label: 'ADAP suppression loss', keyPrefix: 'a', default: 50, unit: '%' },
      { id: 'oahs_loss', label: 'OAHS suppression loss', keyPrefix: 'o', default: 30, unit: '%' },
      { id: 'other_loss', label: 'Other suppression loss', keyPrefix: 'r', default: 40, unit: '%' },
    ],
  },
};

export const cdcTestingConfig: ModelConfig = {
  id: 'cdc-testing',
  name: 'CDC Testing Model Explorer',
  shortName: 'CDC Testing',
  description: 'Analysis of CDC-funded HIV testing program scenarios across 18 US states',

  geographyType: 'state',
  geographyLabel: 'State',
  geographyLabelPlural: 'States',

  locations: ['AL', 'AZ', 'CA', 'FL', 'GA', 'IL', 'KY', 'LA', 'MD', 'MO', 'MS', 'NY', 'OH', 'SC', 'TN', 'TX', 'WA', 'WI'],

  dataUrl: 'https://d320iym4dtm9lj.cloudfront.net/cdc-testing',
  summaryFileName: 'state-summaries.json',

  scenarios: [
    {
      id: 'cessation',
      label: 'Cessation',
      description: 'Complete cessation of CDC-funded testing',
    },
    {
      id: 'brief_interruption',
      label: 'Brief Interruption',
      description: 'Brief interruption of CDC-funded testing',
    },
    {
      id: 'prolonged_interruption',
      label: 'Prolonged Interruption',
      description: 'Prolonged interruption of CDC-funded testing',
    },
  ],

  defaults: {
    outcome: 'incidence',
    statistic: 'mean.and.interval',
  },

  facetDimensions: ['age', 'sex', 'race', 'risk'],

  map: {
    center: [-96.5, 38.5],
    zoom: 4.1,
  },

  interventionStartYear: 2025,

  customSimulation: {
    parameters: [
      { id: 'testing_reduction', label: 'CDC testing reduction', keyPrefix: 't', default: 100, unit: '%' },
      { id: 'proportion_tested_regardless', label: 'Continue testing without CDC', keyPrefix: 'p', default: 50, unit: '%' },
    ],
  },
};

// =============================================================================
// CONFIG REGISTRY
// =============================================================================

export const modelConfigs: Record<string, ModelConfig> = {
  'ryan-white': ryanWhiteConfig,
  'ryan-white-state-ajph': ajphStateLevelConfig,
  'ryan-white-state-croi': croiStateLevelConfig,
  'cdc-testing': cdcTestingConfig,
};

export function getModelConfig(modelId: string): ModelConfig | undefined {
  return modelConfigs[modelId];
}
